"""
Alpaca Trading API client.

Deliberately a thin wrapper over `requests` (pre-installed in the container)
rather than the alpaca-py SDK: no install step on deploy, and a small resident
set inside a 512 MB allocation. Only ever points at the paper endpoint.
"""

import requests

TRADING_BASE = "https://paper-api.alpaca.markets"
DATA_BASE = "https://data.alpaca.markets/v1beta3/crypto/us"

# Activity types that represent money entering or leaving the account, as
# opposed to money made or lost trading. Time-weighted return needs these to
# tell a deposit from a profit. DIV/INT/FEE are excluded on purpose - they are
# returns generated by the portfolio, not external contributions.
CASH_FLOW_TYPES = ("CSD", "CSW", "JNLC", "JNLS", "ACATC", "ACATS")


class Alpaca:
    def __init__(self, key_id, secret_key):
        self.session = requests.Session()
        self.session.headers.update({
            "APCA-API-KEY-ID": key_id,
            "APCA-API-SECRET-KEY": secret_key,
        })

    def _request(self, method, path, **kwargs):
        resp = self.session.request(method, TRADING_BASE + path, timeout=15, **kwargs)
        if resp.status_code >= 400:
            raise RuntimeError(f"{method} {path} -> {resp.status_code} {resp.text[:200]}")
        return resp.json() if resp.text else {}

    # --- account & positions ------------------------------------------------

    def account(self):
        return self._request("GET", "/v2/account")

    def positions(self):
        return self._request("GET", "/v2/positions")

    # --- orders -------------------------------------------------------------

    def open_orders(self):
        return self._request("GET", "/v2/orders", params={"status": "open"})

    def get_order(self, order_id):
        return self._request("GET", f"/v2/orders/{order_id}")

    def cancel_all_orders(self):
        self.session.delete(TRADING_BASE + "/v2/orders", timeout=15)

    def close_position(self, position_symbol):
        """Liquidate the whole position. Preferred over selling a computed
        quantity: Alpaca deducts its crypto fee from the filled quantity, so the
        position is always slightly smaller than the amount ordered."""
        return self._request("DELETE", f"/v2/positions/{position_symbol}")

    def submit_order(self, symbol, qty, side):
        return self._request("POST", "/v2/orders", json={
            "symbol": symbol,
            "qty": str(qty),
            "side": side,
            "type": "market",
            "time_in_force": "gtc",  # crypto rejects "day"
        })

    # --- activities ---------------------------------------------------------

    def activities(self, types, after_iso=None, page_token=None):
        """One page (max 100) of account activities, oldest first. Paging is
        cursor-based: pass the last row's id back as page_token."""
        params = {
            "activity_types": ",".join(types),
            "direction": "asc",
            "page_size": 100,
        }
        if after_iso:
            params["after"] = after_iso
        if page_token:
            params["page_token"] = page_token
        rows = self._request("GET", "/v2/account/activities", params=params)
        return rows if isinstance(rows, list) else []


def fetch_closes(symbol, timeframe, limit):
    """Crypto market data is public - no credentials required."""
    resp = requests.get(
        f"{DATA_BASE}/bars",
        params={"symbols": symbol, "timeframe": timeframe, "limit": limit},
        timeout=15,
    )
    resp.raise_for_status()
    bars = resp.json().get("bars", {}).get(symbol, [])
    return [bar["c"] for bar in bars]
