"""
Alpaca Trading API client - every HTTP call to the broker lives here.

Deliberately a thin wrapper over `requests` (pre-installed in the container)
rather than the alpaca-py SDK: no install step on deploy, and a small resident
set inside a 512 MB allocation. Only ever points at the paper endpoint.

Market data (bars, latest quote) is public on Alpaca's crypto data API and
needs no credentials; it is exposed as methods here anyway so the engine has
one object to talk to and tests can substitute a fake broker wholesale.
"""

from decimal import ROUND_DOWN, Decimal

import requests

TRADING_BASE = "https://paper-api.alpaca.markets"
DATA_BASE = "https://data.alpaca.markets/v1beta3/crypto/us"

# Activity types that represent money entering or leaving the account, as
# opposed to money made or lost trading. Time-weighted return needs these to
# tell a deposit from a profit. DIV/INT/FEE are excluded on purpose - they are
# returns generated by the portfolio, not external contributions.
CASH_FLOW_TYPES = ("CSD", "CSW", "JNLC", "JNLS", "ACATC", "ACATS")

QTY_STEP = Decimal("0.000000001")   # Alpaca reports crypto positions to 9 dp
PRICE_DP = 2                        # BTC/USD prices to the cent


def fmt_qty(qty):
    """Format a quantity for the wire, flooring rather than rounding.

    A sell for a hair more than the position is rejected outright ("insufficient
    balance"); a buy for a hair less is harmless. Flooring to the venue's own
    precision also lets a take-profit be sized to exactly the position Alpaca
    reports, dust and all."""
    d = Decimal(str(qty)).quantize(QTY_STEP, rounding=ROUND_DOWN)
    s = format(d, "f").rstrip("0").rstrip(".")
    return s if s and s != "-0" else "0"


def fmt_price(price):
    return f"{round(float(price), PRICE_DP):.{PRICE_DP}f}"


class Alpaca:
    def __init__(self, key_id, secret_key):
        self.session = requests.Session()
        self.session.headers.update({
            "APCA-API-KEY-ID": key_id,
            "APCA-API-SECRET-KEY": secret_key,
        })

    def _request(self, method, path, **kwargs):
        resp = self.session.request(method, TRADING_BASE + path, timeout=15, **kwargs)
        if resp.status_code >= 400:
            raise RuntimeError(f"{method} {path} -> {resp.status_code} {resp.text[:200]}")
        return resp.json() if resp.text else {}

    # --- account & positions ------------------------------------------------

    def account(self):
        return self._request("GET", "/v2/account")

    def positions(self):
        return self._request("GET", "/v2/positions")

    # --- orders -------------------------------------------------------------

    def open_orders(self):
        return self._request("GET", "/v2/orders", params={"status": "open", "limit": 200})

    def get_order(self, order_id):
        return self._request("GET", f"/v2/orders/{order_id}")

    def cancel_order(self, order_id):
        """Cancel one order. Alpaca answers 204 on success and 422 when the
        order is already in a terminal state - both are fine for a caller that
        just wants it not to be resting any more."""
        resp = self.session.delete(f"{TRADING_BASE}/v2/orders/{order_id}", timeout=15)
        if resp.status_code not in (200, 204, 404, 422):
            raise RuntimeError(f"DELETE /v2/orders/{order_id} -> {resp.status_code} {resp.text[:200]}")

    def cancel_all_orders(self):
        self.session.delete(TRADING_BASE + "/v2/orders", timeout=15)

    def close_position(self, position_symbol):
        """Liquidate the whole position at market. Preferred over selling a
        computed quantity: Alpaca deducts its crypto fee from the filled
        quantity, so the position is always slightly smaller than the amount
        ordered."""
        return self._request("DELETE", f"/v2/positions/{position_symbol}")

    def submit_market_order(self, symbol, qty, side):
        return self._request("POST", "/v2/orders", json={
            "symbol": symbol,
            "qty": fmt_qty(qty),
            "side": side,
            "type": "market",
            "time_in_force": "gtc",  # crypto rejects "day"
        })

    def submit_limit_order(self, symbol, qty, side, limit_price):
        """A resting limit order. The ladder's safety levels and the take-profit
        are all limits: they wait at the price rather than chasing it, and a
        resting fill is charged the lower maker fee."""
        return self._request("POST", "/v2/orders", json={
            "symbol": symbol,
            "qty": fmt_qty(qty),
            "side": side,
            "type": "limit",
            "limit_price": fmt_price(limit_price),
            "time_in_force": "gtc",
        })

    # --- activities ---------------------------------------------------------

    def activities(self, types, after_iso=None, page_token=None):
        """One page (max 100) of account activities, oldest first. Paging is
        cursor-based: pass the last row's id back as page_token."""
        params = {
            "activity_types": ",".join(types),
            "direction": "asc",
            "page_size": 100,
        }
        if after_iso:
            params["after"] = after_iso
        if page_token:
            params["page_token"] = page_token
        rows = self._request("GET", "/v2/account/activities", params=params)
        return rows if isinstance(rows, list) else []

    # --- public market data -------------------------------------------------

    def fetch_bars(self, symbol, timeframe, limit):
        """Recent OHLCV bars, ascending by time. Public endpoint."""
        resp = requests.get(
            f"{DATA_BASE}/bars",
            params={"symbols": symbol, "timeframe": timeframe, "limit": limit},
            timeout=15,
        )
        resp.raise_for_status()
        bars = resp.json().get("bars", {}).get(symbol, [])
        return sorted(bars, key=lambda b: b["t"])

    def latest_quote(self, symbol):
        """Best bid/ask and their midpoint. Public endpoint."""
        resp = requests.get(
            f"{DATA_BASE}/latest/quotes", params={"symbols": symbol}, timeout=15
        )
        resp.raise_for_status()
        q = resp.json().get("quotes", {}).get(symbol)
        if not q:
            return None
        ask, bid = float(q.get("ap") or 0), float(q.get("bp") or 0)
        mid = (ask + bid) / 2 if ask and bid else (ask or bid or None)
        return {"ap": ask, "bp": bid, "mid": mid, "t": q.get("t")}
